### PR TITLE
Proposal for fixing #6 and #7

### PR DESCRIPTION
**Pull request by Oitzu**

### CODE REVIEW

**Comment by krzychb** [comment]
Hi @Oitzu,

Nice fix!

I did quick check for:

- live image
- test pattern
- OV7725 camera
- XCLK @40MHz

It works without any issues.
I think these commits should be squashed.
Thank you for adding comments.

**Comment by igrr** [comment]
Looks good! As @krzychb said, please squash "whoopsie.." commit :)

**Comment by Oitzu** [comment]
Erghs i fucked the squash up. :(

**Comment by Oitzu** [comment]
Okay. This looks better. Squashed like my hope and dreams for the glory of the clean commit god. ;)

**Pull request merged**
